#!/bin/bash

# Build and start template container
echo 'Starting template container...'
docker-compose up -d --build template
echo 'Waiting for database to start...'
sleep 5
# Import database dump
echo 'Import DB dump...'
docker-compose exec -u postgres -w '/var/lib/postgresql' template /bin/sh -c 'pg_restore -d ichiran --no-privileges --no-owner ichiran.pgdump'
# Remove dump and entry script
docker-compose exec -w '/var/lib/postgresql' template /bin/sh -c 'rm -rf /docker-entrypoint-initdb.d/* && rm -f ichiran.pgdump'
# Run build script
docker-compose exec -w '/var/lib/ichiran-cli' template /bin/sh -c './build-cli.sh'
# Stop postgresql service to prevent database corruption
docker-compose stop template
# Create image from CLI container
echo 'Writing final CLI image...'
# Container name is hard-coded for now to match name generated by docker-compose
# That means the folder containing the build needs to be named ichiran-cli-docker
docker commit ichiran-cli-docker_template_1 sissbruecker/ichiran-cli:latest
