#!/bin/bash

# Build and start template container
echo 'Starting database template container...'
docker-compose up -d --build database
echo 'Waiting for database to start...'
sleep 5
# Import database dump
echo 'Import DB dump...'
docker-compose exec -u postgres database /bin/sh -c 'pg_restore -d ichiran --no-privileges --no-owner ichiran.pgdump'
# Remove dump and entry script
docker-compose exec database /bin/sh -c 'rm -rf /docker-entrypoint-initdb.d/*'
docker-compose exec database /bin/sh -c 'rm -f ichiran.pgdump'
# Stop postgresql service to prevent database corruption
docker-compose exec -u postgres database /bin/sh -c 'pg_ctl stop'
# Create image from seeded database container
echo 'Writing final database image...'
docker commit ichiran-cli-docker_database_1 sissbruecker/ichiran-db:latest # Container name is hard-coded for now to match name generated by docker-compose