version: "3.9"

services:
  # Template image that is used as a starting point for building the CLI image
  template:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        DB_DUMP_PATH: ${DB_DUMP_PATH}
        JM_DICT_DB_PATH: ${JM_DICT_DB_PATH}
  # Final CLI image
  cli:
    image: sissbruecker/ichiran-cli:latest

